<?php
/* 
Write a piece of PHP code for a website with the following requirements:

The webpage is in English.
The website is called AI Open Center and has the domain name AIOpenCenter.com.
The code should be as concise as possible.
Do not write any unnecessary code.
Styles should be written inline in elements.
Use the following links to import external libraries: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.min.js for Bootstrap without the integrity parameter, and https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js for jQuery.
All fonts should be from the Google Font Montserrat.
The webpage should use Bootstrap for responsive design.
The primary color is #007bff, and the secondary color is #212529.
The webpage should have a footer tag that is responsive and located at the bottom of the page. At the top of the footer, there should be a horizontal line. On the left side of the line, there should be a copyright notice that reads, 'The world's first website completely generated by AI.' On the right side of the line, there should be a prompt that reads 'Feedback Welcome' followed by a Twitter address 'https://twitter.com/IronEaterBeast'. Below that, there should be a brief explanation of the project, followed by an image linking to the project's GitHub address 'https://github.com/IronEaterBeast/The-world-s-first-website-completely-generated-by-AI'.

写一段网站的php代码，要求：
页面是英文的
网站名字是AI Open Center，域名是AIOpenCenter.com
代码尽量精简
不要编写没有提到的内容
样式直接写到元素里面
引入bootstrap是https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.3/js/bootstrap.min.js，不要有integrity参数
引入jquery是https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js
所有字体使用谷歌字体的Montserrat
页面使用bootstrap来完成自适应
当说到主要颜色时是指颜色007bff，当说到次要颜色时是指颜色212529
使用bootstrap的footer标签的自适应的页面底部，在顶部添加一条分割线，左边是版权信息“The world's first website completely generated by AI”，右边是欢迎反馈然后紧跟twitter地址“https://twitter.com/IronEaterBeast”，然后是说明这个项目的github地址，用一张github的图片链接到“https://github.com/IronEaterBeast/The-world-s-first-website-completely-generated-by-AI”
*/
?>
	<footer class="bg-light py-3">
    <div class="container border-top py-2 d-flex justify-content-between align-items-center">
      <div class="text-muted">The world's first website completely generated by AI</div>
      <div>
        <span class="text-muted me-2">Welcome feedback: </span>
        <a href="https://twitter.com/IronEaterBeast">@IronEaterBeast</a>
        <span class="text-muted ms-2 me-3">|</span>
        Project's Github: <a href="https://github.com/IronEaterBeast/The-world-s-first-website-completely-generated-by-AI">
          <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github" width="24" height="24">
        </a>
      </div>
    </div>
  </footer>
</body>

</html>